window.Vue = require('vue');
require('./pages/theme');
require('./pages/article/create_edit_article');
require('./pages/article/create_edit_page');
require('./pages/article/index_article');
require('./pages/category/create_edit_category');
require('./pages/category/index_category');
require('./pages/setting/menu');
require('./pages/setting/setting_site');
require('./pages/user/index_user');
require('./pages/advertising/index_advertising');
require('./pages/advertising/create_update_advertising');
require('./pages/partner/index_partner');
require('./pages/partner/create_update_partner');
